// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: proto/keys.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Curve25519Public []byte                 `protobuf:"bytes,1,opt,name=curve25519_public,json=curve25519Public,proto3" json:"curve25519_public,omitempty"` // 32 bytes
	Ed25519Public    []byte                 `protobuf:"bytes,2,opt,name=ed25519_public,json=ed25519Public,proto3" json:"ed25519_public,omitempty"`          // 32 bytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentityKey) Reset() {
	*x = IdentityKey{}
	mi := &file_proto_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKey) ProtoMessage() {}

func (x *IdentityKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKey.ProtoReflect.Descriptor instead.
func (*IdentityKey) Descriptor() ([]byte, []int) {
	return file_proto_keys_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityKey) GetCurve25519Public() []byte {
	if x != nil {
		return x.Curve25519Public
	}
	return nil
}

func (x *IdentityKey) GetEd25519Public() []byte {
	if x != nil {
		return x.Ed25519Public
	}
	return nil
}

type PreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreKey) Reset() {
	*x = PreKey{}
	mi := &file_proto_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKey) ProtoMessage() {}

func (x *PreKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKey.ProtoReflect.Descriptor instead.
func (*PreKey) Descriptor() ([]byte, []int) {
	return file_proto_keys_proto_rawDescGZIP(), []int{1}
}

func (x *PreKey) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignedPreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPreKey) Reset() {
	*x = SignedPreKey{}
	mi := &file_proto_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPreKey) ProtoMessage() {}

func (x *SignedPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPreKey.ProtoReflect.Descriptor instead.
func (*SignedPreKey) Descriptor() ([]byte, []int) {
	return file_proto_keys_proto_rawDescGZIP(), []int{2}
}

func (x *SignedPreKey) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SignedPreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPreKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PreKeyBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId uint32                 `protobuf:"varint,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	DeviceId       uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PreKey         *PreKey                `protobuf:"bytes,3,opt,name=pre_key,json=preKey,proto3" json:"pre_key,omitempty"` // optional: omit for one-time pre-key absence
	SignedPreKey   *SignedPreKey          `protobuf:"bytes,4,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	IdentityKey    *IdentityKey           `protobuf:"bytes,5,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_proto_keys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_proto_keys_proto_rawDescGZIP(), []int{3}
}

func (x *PreKeyBundle) GetRegistrationId() uint32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

func (x *PreKeyBundle) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PreKeyBundle) GetPreKey() *PreKey {
	if x != nil {
		return x.PreKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKey() *SignedPreKey {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *PreKeyBundle) GetIdentityKey() *IdentityKey {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

var File_proto_keys_proto protoreflect.FileDescriptor

const file_proto_keys_proto_rawDesc = "" +
	"\n" +
	"\x10proto/keys.proto\x12\vsignal.keys\"a\n" +
	"\vIdentityKey\x12+\n" +
	"\x11curve25519_public\x18\x01 \x01(\fR\x10curve25519Public\x12%\n" +
	"\x0eed25519_public\x18\x02 \x01(\fR\red25519Public\"7\n" +
	"\x06PreKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"[\n" +
	"\fSignedPreKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x80\x02\n" +
	"\fPreKeyBundle\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\rR\x0eregistrationId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12,\n" +
	"\apre_key\x18\x03 \x01(\v2\x13.signal.keys.PreKeyR\x06preKey\x12?\n" +
	"\x0esigned_pre_key\x18\x04 \x01(\v2\x19.signal.keys.SignedPreKeyR\fsignedPreKey\x12;\n" +
	"\fidentity_key\x18\x05 \x01(\v2\x18.signal.keys.IdentityKeyR\videntityKeyB&Z$github.com/deicod/signal/proto;protob\x06proto3"

var (
	file_proto_keys_proto_rawDescOnce sync.Once
	file_proto_keys_proto_rawDescData []byte
)

func file_proto_keys_proto_rawDescGZIP() []byte {
	file_proto_keys_proto_rawDescOnce.Do(func() {
		file_proto_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keys_proto_rawDesc), len(file_proto_keys_proto_rawDesc)))
	})
	return file_proto_keys_proto_rawDescData
}

var file_proto_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_keys_proto_goTypes = []any{
	(*IdentityKey)(nil),  // 0: signal.keys.IdentityKey
	(*PreKey)(nil),       // 1: signal.keys.PreKey
	(*SignedPreKey)(nil), // 2: signal.keys.SignedPreKey
	(*PreKeyBundle)(nil), // 3: signal.keys.PreKeyBundle
}
var file_proto_keys_proto_depIdxs = []int32{
	1, // 0: signal.keys.PreKeyBundle.pre_key:type_name -> signal.keys.PreKey
	2, // 1: signal.keys.PreKeyBundle.signed_pre_key:type_name -> signal.keys.SignedPreKey
	0, // 2: signal.keys.PreKeyBundle.identity_key:type_name -> signal.keys.IdentityKey
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_keys_proto_init() }
func file_proto_keys_proto_init() {
	if File_proto_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keys_proto_rawDesc), len(file_proto_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_keys_proto_goTypes,
		DependencyIndexes: file_proto_keys_proto_depIdxs,
		MessageInfos:      file_proto_keys_proto_msgTypes,
	}.Build()
	File_proto_keys_proto = out.File
	file_proto_keys_proto_goTypes = nil
	file_proto_keys_proto_depIdxs = nil
}
