// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: proto/wire.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RatchetKey      []byte                 `protobuf:"bytes,1,opt,name=ratchet_key,json=ratchetKey" json:"ratchet_key,omitempty"`
	Counter         *uint32                `protobuf:"varint,2,opt,name=counter" json:"counter,omitempty"`
	PreviousCounter *uint32                `protobuf:"varint,3,opt,name=previous_counter,json=previousCounter" json:"previous_counter,omitempty"`
	Ciphertext      []byte                 `protobuf:"bytes,4,opt,name=ciphertext" json:"ciphertext,omitempty"`
	PqRatchet       []byte                 `protobuf:"bytes,5,opt,name=pq_ratchet,json=pqRatchet" json:"pq_ratchet,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_proto_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_proto_wire_proto_rawDescGZIP(), []int{0}
}

func (x *SignalMessage) GetRatchetKey() []byte {
	if x != nil {
		return x.RatchetKey
	}
	return nil
}

func (x *SignalMessage) GetCounter() uint32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

func (x *SignalMessage) GetPreviousCounter() uint32 {
	if x != nil && x.PreviousCounter != nil {
		return *x.PreviousCounter
	}
	return 0
}

func (x *SignalMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SignalMessage) GetPqRatchet() []byte {
	if x != nil {
		return x.PqRatchet
	}
	return nil
}

type PreKeySignalMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId  *uint32                `protobuf:"varint,5,opt,name=registration_id,json=registrationId" json:"registration_id,omitempty"`
	PreKeyId        *uint32                `protobuf:"varint,1,opt,name=pre_key_id,json=preKeyId" json:"pre_key_id,omitempty"`
	SignedPreKeyId  *uint32                `protobuf:"varint,6,opt,name=signed_pre_key_id,json=signedPreKeyId" json:"signed_pre_key_id,omitempty"`
	KyberPreKeyId   *uint32                `protobuf:"varint,7,opt,name=kyber_pre_key_id,json=kyberPreKeyId" json:"kyber_pre_key_id,omitempty"`
	KyberCiphertext []byte                 `protobuf:"bytes,8,opt,name=kyber_ciphertext,json=kyberCiphertext" json:"kyber_ciphertext,omitempty"`
	BaseKey         []byte                 `protobuf:"bytes,2,opt,name=base_key,json=baseKey" json:"base_key,omitempty"`
	IdentityKey     []byte                 `protobuf:"bytes,3,opt,name=identity_key,json=identityKey" json:"identity_key,omitempty"`
	Message         []byte                 `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"` // SignalMessage
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreKeySignalMessage) Reset() {
	*x = PreKeySignalMessage{}
	mi := &file_proto_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeySignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeySignalMessage) ProtoMessage() {}

func (x *PreKeySignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeySignalMessage.ProtoReflect.Descriptor instead.
func (*PreKeySignalMessage) Descriptor() ([]byte, []int) {
	return file_proto_wire_proto_rawDescGZIP(), []int{1}
}

func (x *PreKeySignalMessage) GetRegistrationId() uint32 {
	if x != nil && x.RegistrationId != nil {
		return *x.RegistrationId
	}
	return 0
}

func (x *PreKeySignalMessage) GetPreKeyId() uint32 {
	if x != nil && x.PreKeyId != nil {
		return *x.PreKeyId
	}
	return 0
}

func (x *PreKeySignalMessage) GetSignedPreKeyId() uint32 {
	if x != nil && x.SignedPreKeyId != nil {
		return *x.SignedPreKeyId
	}
	return 0
}

func (x *PreKeySignalMessage) GetKyberPreKeyId() uint32 {
	if x != nil && x.KyberPreKeyId != nil {
		return *x.KyberPreKeyId
	}
	return 0
}

func (x *PreKeySignalMessage) GetKyberCiphertext() []byte {
	if x != nil {
		return x.KyberCiphertext
	}
	return nil
}

func (x *PreKeySignalMessage) GetBaseKey() []byte {
	if x != nil {
		return x.BaseKey
	}
	return nil
}

func (x *PreKeySignalMessage) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PreKeySignalMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SenderKeyMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DistributionUuid []byte                 `protobuf:"bytes,1,opt,name=distribution_uuid,json=distributionUuid" json:"distribution_uuid,omitempty"`
	ChainId          *uint32                `protobuf:"varint,2,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Iteration        *uint32                `protobuf:"varint,3,opt,name=iteration" json:"iteration,omitempty"`
	Ciphertext       []byte                 `protobuf:"bytes,4,opt,name=ciphertext" json:"ciphertext,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SenderKeyMessage) Reset() {
	*x = SenderKeyMessage{}
	mi := &file_proto_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyMessage) ProtoMessage() {}

func (x *SenderKeyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyMessage.ProtoReflect.Descriptor instead.
func (*SenderKeyMessage) Descriptor() ([]byte, []int) {
	return file_proto_wire_proto_rawDescGZIP(), []int{2}
}

func (x *SenderKeyMessage) GetDistributionUuid() []byte {
	if x != nil {
		return x.DistributionUuid
	}
	return nil
}

func (x *SenderKeyMessage) GetChainId() uint32 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *SenderKeyMessage) GetIteration() uint32 {
	if x != nil && x.Iteration != nil {
		return *x.Iteration
	}
	return 0
}

func (x *SenderKeyMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type SenderKeyDistributionMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DistributionUuid []byte                 `protobuf:"bytes,1,opt,name=distribution_uuid,json=distributionUuid" json:"distribution_uuid,omitempty"`
	ChainId          *uint32                `protobuf:"varint,2,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Iteration        *uint32                `protobuf:"varint,3,opt,name=iteration" json:"iteration,omitempty"`
	ChainKey         []byte                 `protobuf:"bytes,4,opt,name=chain_key,json=chainKey" json:"chain_key,omitempty"`
	SigningKey       []byte                 `protobuf:"bytes,5,opt,name=signing_key,json=signingKey" json:"signing_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SenderKeyDistributionMessage) Reset() {
	*x = SenderKeyDistributionMessage{}
	mi := &file_proto_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyDistributionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyDistributionMessage) ProtoMessage() {}

func (x *SenderKeyDistributionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyDistributionMessage.ProtoReflect.Descriptor instead.
func (*SenderKeyDistributionMessage) Descriptor() ([]byte, []int) {
	return file_proto_wire_proto_rawDescGZIP(), []int{3}
}

func (x *SenderKeyDistributionMessage) GetDistributionUuid() []byte {
	if x != nil {
		return x.DistributionUuid
	}
	return nil
}

func (x *SenderKeyDistributionMessage) GetChainId() uint32 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *SenderKeyDistributionMessage) GetIteration() uint32 {
	if x != nil && x.Iteration != nil {
		return *x.Iteration
	}
	return 0
}

func (x *SenderKeyDistributionMessage) GetChainKey() []byte {
	if x != nil {
		return x.ChainKey
	}
	return nil
}

func (x *SenderKeyDistributionMessage) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

var File_proto_wire_proto protoreflect.FileDescriptor

const file_proto_wire_proto_rawDesc = "" +
	"\n" +
	"\x10proto/wire.proto\x12\x11signal.proto.wire\"\xb4\x01\n" +
	"\rSignalMessage\x12\x1f\n" +
	"\vratchet_key\x18\x01 \x01(\fR\n" +
	"ratchetKey\x12\x18\n" +
	"\acounter\x18\x02 \x01(\rR\acounter\x12)\n" +
	"\x10previous_counter\x18\x03 \x01(\rR\x0fpreviousCounter\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1d\n" +
	"\n" +
	"pq_ratchet\x18\x05 \x01(\fR\tpqRatchet\"\xb3\x02\n" +
	"\x13PreKeySignalMessage\x12'\n" +
	"\x0fregistration_id\x18\x05 \x01(\rR\x0eregistrationId\x12\x1c\n" +
	"\n" +
	"pre_key_id\x18\x01 \x01(\rR\bpreKeyId\x12)\n" +
	"\x11signed_pre_key_id\x18\x06 \x01(\rR\x0esignedPreKeyId\x12'\n" +
	"\x10kyber_pre_key_id\x18\a \x01(\rR\rkyberPreKeyId\x12)\n" +
	"\x10kyber_ciphertext\x18\b \x01(\fR\x0fkyberCiphertext\x12\x19\n" +
	"\bbase_key\x18\x02 \x01(\fR\abaseKey\x12!\n" +
	"\fidentity_key\x18\x03 \x01(\fR\videntityKey\x12\x18\n" +
	"\amessage\x18\x04 \x01(\fR\amessage\"\x98\x01\n" +
	"\x10SenderKeyMessage\x12+\n" +
	"\x11distribution_uuid\x18\x01 \x01(\fR\x10distributionUuid\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\rR\achainId\x12\x1c\n" +
	"\titeration\x18\x03 \x01(\rR\titeration\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\"\xc2\x01\n" +
	"\x1cSenderKeyDistributionMessage\x12+\n" +
	"\x11distribution_uuid\x18\x01 \x01(\fR\x10distributionUuid\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\rR\achainId\x12\x1c\n" +
	"\titeration\x18\x03 \x01(\rR\titeration\x12\x1b\n" +
	"\tchain_key\x18\x04 \x01(\fR\bchainKey\x12\x1f\n" +
	"\vsigning_key\x18\x05 \x01(\fR\n" +
	"signingKeyB&Z$github.com/deicod/signal/proto;proto"

var (
	file_proto_wire_proto_rawDescOnce sync.Once
	file_proto_wire_proto_rawDescData []byte
)

func file_proto_wire_proto_rawDescGZIP() []byte {
	file_proto_wire_proto_rawDescOnce.Do(func() {
		file_proto_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wire_proto_rawDesc), len(file_proto_wire_proto_rawDesc)))
	})
	return file_proto_wire_proto_rawDescData
}

var file_proto_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_wire_proto_goTypes = []any{
	(*SignalMessage)(nil),                // 0: signal.proto.wire.SignalMessage
	(*PreKeySignalMessage)(nil),          // 1: signal.proto.wire.PreKeySignalMessage
	(*SenderKeyMessage)(nil),             // 2: signal.proto.wire.SenderKeyMessage
	(*SenderKeyDistributionMessage)(nil), // 3: signal.proto.wire.SenderKeyDistributionMessage
}
var file_proto_wire_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wire_proto_init() }
func file_proto_wire_proto_init() {
	if File_proto_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wire_proto_rawDesc), len(file_proto_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wire_proto_goTypes,
		DependencyIndexes: file_proto_wire_proto_depIdxs,
		MessageInfos:      file_proto_wire_proto_msgTypes,
	}.Build()
	File_proto_wire_proto = out.File
	file_proto_wire_proto_goTypes = nil
	file_proto_wire_proto_depIdxs = nil
}
